config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :users

  resources :clients do
    resources :contacts, only: %i[new create]
  end

  resources :contacts, only: %i[show edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :name, :email, :phone, presence: true
  has_many :contacts, dependent: :destroy
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :phone, presence: true
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @clients = Client.all
  end

  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = 'Cliente cadastrado com sucesso!'
      redirect_to @client
    else
      flash.now[:alert] = 'Cliente não foi cadastrado. Corrija os erros!'
      render :new
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:notice] = 'Cliente atualizado com sucesso!'
      redirect_to @client
    else
      flash.now[:alert] = 'Cliente não foi atualizado. Corrija os erros!'
      render :edit
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    flash[:notice] = 'O cliente foi excluido.'
    render :index
  end

  private

  def client_params
    params.require(:client).permit(:name, :email, :secondary_email, :phone,
                                   :comercial_phone)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @client = Client.find(params[:client_id])
    @contact = Contact.new
  end

  def create
    @client = Client.find(params[:client_id])
    @contact = @client.contacts.new(contact_params)
    if @contact.save
      flash[:notice] = 'Contato registrado com sucesso!'
      redirect_to @contact
    else
      flash[:alert] = 'Contato não registrado. Corrija os erros!'
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      flash[:notice] = 'Contato atualizado com sucesso!'
      redirect_to @contact
    else
      flash[:alert] = 'Contato não atualizado. Corrija os erros!'
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @client = @contact.client
    @contact.destroy
    flash[:notice] = 'O contato foi excluido!'
    redirect_to @client
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :secondary_email, :phone,
                                    :comercial_phone)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_form.html.erb
<div class="d-flex justify-content-center mt-4">
  <div class="col-md-4 card p-5">
    <% if @client.errors.any? %>
      <ul>
        <% @client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for @client do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :secondary_email %>
        <%= f.email_field :secondary_email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :comercial_phone %>
        <%= f.text_field :comercial_phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Salvar', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/edit.html.erb
<h1>Atualizar Cliente</h1>

<%= render partial: 'form' %>

<%= link_to 'Voltar', :back, class: 'btn btn-light' %>

app/views/clients/index.html.erb
<h1>Lista de clientes</h1>

<%= link_to 'Cadastrar Cliente', new_client_path, class: 'btn btn-primary'  %>

<hr>

<div class="row justify-content-md-center">
  <% if @clients.present? %>
    <% @clients.each do |c| %>
      <div class="card col-md-3 m-5 p-0">
        <div class="card-body">
            <h5 class="card-title"><%= t('clients.name') %>: <%= link_to c.name, client_path(c) %></h5>
            <p class="card-text">
              <span class="fa fa-phone"></span>
              <strong><%= t('clients.phone') %></strong>: <%= c.phone %>
            </p>
            <p class="card-text">
              <span class="fa fa-phone"></span>
              <strong><%= t('clients.comercial_phone') %>:</strong> <%= c.comercial_phone %>
            </p>
            <p class="card-text">
              <span class="fa fa-envelope"></span>
              <strong><%= t('clients.email') %>:</strong> <%= c.email %>
            </p>
            <p class="card-text">
              <span class="fa fa-envelope"></span>
              <strong><%= t('clients.secondary_email') %>:</strong> <%= c.secondary_email %></li>
            </p>
            <p class="card-text">
              <strong><%= t('clients.created_at') %>:</strong> <%= l(c.created_at, format: :long) %>
            </p>
          </div>
      </div>
    <% end %>
  <% else %>
    <span>Não há clientes registrados!</span>
  <% end %>

</div>
<%= link_to 'Voltar', root_path, class: 'btn btn-light' %>

app/views/clients/new.html.erb
<h1>Cadastro de Clientes</h1>

<%= render partial: 'form' %>

<%= link_to 'Voltar', :back, class: 'btn btn-light' %>

app/views/clients/show.html.erb
<h1>Cliente: <%= @client.name %></h1>

<hr>

<%= link_to 'Editar Cliente', edit_client_path(@client), class: 'btn btn-primary mb-2' %>

<dl>
  <dt><%= t('clients.name') %>:</dt>
  <dd><%= @client.name %></dd>
  <dt><%= t('clients.email') %>:</dt>
  <dd><%= @client.email %></dd>
  <dt><%= t('clients.secondary_email') %>:</dt>
  <dd><%= @client.secondary_email %></dd>
  <dt><%= t('clients.phone') %>:</dt>
  <dd><%= @client.phone %></dd>
  <dt><%= t('clients.comercial_phone') %>:</dt>
  <dd><%= @client.comercial_phone %></dd>
</dl>

<%= link_to 'Excluir Cliente', client_path(@client), method: :delete, class: 'btn btn-danger'  %>
</div>

<div class="container-fluid mt-3">
<h3>Contatos</h3>

<hr>

<%= link_to 'Adicionar Contato', new_client_contact_path(@client), class: 'btn btn-primary'  %>
<div class="row justify-content-md-center">
  <% if @client.contacts.present? %>
    <% @client.contacts.each do |c| %>
      <div class="card col-md-3 m-5 p-0">
        <div class="card-body">
            <h5 class="card-title"><%= t('contacts.name') %>: <%= link_to c.name, contact_path(c) %></h5>
            <p class="card-text">
              <span class="fa fa-phone"></span>
              <strong><%= t('contacts.phone') %></strong>: <%= c.phone %>
            </p>
            <p class="card-text">
              <span class="fa fa-phone"></span>
              <strong><%= t('contacts.comercial_phone') %>:</strong> <%= c.comercial_phone %>
            </p>
            <p class="card-text">
              <span class="fa fa-envelope"></span>
              <strong><%= t('contacts.email') %>:</strong> <%= c.email %>
            </p>
            <p class="card-text">
              <span class="fa fa-envelope"></span>
              <strong><%= t('contacts.secondary_email') %>:</strong> <%= c.secondary_email %></li>
            </p>
            <p class="card-text">
              <strong><%= t('contacts.created_at') %>:</strong> <%= l(c.created_at, format: :long) %>
            </p>
            <%= link_to content_tag(:span, '', class: 'fa fa-trash'), contact_path(c), method: :delete, class: 'card-link btn btn-danger', title: 'Excluir Contato' %>
          </div>
      </div>
    <% end %>
  <% else %>
    <span>Não há contatos registrados</span>
  <% end %>
</div>

<%= link_to 'Voltar', clients_path, class: 'btn btn-light' %>

app/views/contacts/_form.html.erb
<div class="d-flex justify-content-center mt-4">
  <div class="col-md-4 card p-5">
    <% if @contact.errors.any? %>
      <ul>
        <% @contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>

    <%= form_for ([@client, @contact]) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :secondary_email %>
        <%= f.email_field :secondary_email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :comercial_phone %>
        <%= f.text_field :comercial_phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Salvar', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<h1>Editar Contato</h1>

<%= render partial: 'form' %>

<%= link_to 'Voltar', :back, class: 'btn btn-light' %>

app/views/contacts/new.html.erb
<h1>Adicionar Contato</h1>

<%= render partial: 'form' %>

<%= link_to 'Voltar', :back, class: 'btn btn-light' %>

app/views/contacts/show.html.erb
<h1>Contato vinculado ao cliente: <%= link_to @contact.client.name, client_path(@contact.client) %></h1>

<hr>

<%= link_to 'Editar Contato', edit_contact_path(@contact), class: 'btn btn-primary mb-2' %>

<dl>
  <dt><%= t('contacts.name') %>:</dt>
  <dd><%= @contact.name %></dd>
  <dt><%= t('contacts.email') %>:</dt>
  <dd><%= @contact.email %></dd>
  <dt><%= t('contacts.secondary_email') %>:</dt>
  <dd><%= @contact.secondary_email %></dd>
  <dt><%= t('contacts.phone') %>:</dt>
  <dd><%= @contact.phone %></dd>
  <dt><%= t('contacts.comercial_phone') %>:</dt>
  <dd><%= @contact.comercial_phone %></dd>
</dl>


<%= link_to 'Excluir Contato', contact_path(@contact), method: :delete, class: 'btn btn-danger'  %>

<hr>

<%= link_to 'Voltar', client_path(@contact.client), class: 'btn btn-light' %>

app/views/home/index.html.erb
<h1>Bem vindo!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio CustomerX</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <p><%= notice %></p>
    <p><%= alert %></p>
    <div class="container-fluid p-3">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'CustomerX', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto">
      <li class="nav-item">
        <%= link_to 'Clientes', clients_path, class: 'nav-link' %>
      </li>
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'nav-link' %>
      <% else %>
      </li>
        <%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %>
      </li>
      <% end %>      
    </ul>
  </div>
</nav>